# Generated by Django 5.0.1 on 2024-01-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_womenproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='womenproduct',
            name='image',
        ),
        migrations.AddField(
            model_name='womenproduct',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
