# Generated by Django 5.0.1 on 2024-01-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_womenproduct_image_womenproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='womenproduct',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='women_products/'),
        ),
        migrations.AlterField(
            model_name='womenproduct',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
