# Generated by Django 5.0.1 on 2024-01-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_womenproduct_image_alter_womenproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womenproduct',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='women_products/'),
        ),
    ]
