# Generated by Django 5.0.1 on 2024-01-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_womenproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womenproduct',
            name='image',
            field=models.ImageField(upload_to='women_products/'),
        ),
    ]
