# Generated by Django 5.0.1 on 2024-01-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_womenproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womenproduct',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='product_images/'),
        ),
    ]
