# Generated by Django 5.0.1 on 2024-01-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_womenproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womenproduct',
            name='image',
            field=models.ImageField(default='default_image.AVIF', upload_to='women_products/'),
        ),
    ]
